// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VanguardTracker.Api.Data;

#nullable disable

namespace VanguardTracker.Api.Migrations
{
    [DbContext(typeof(VanguardDbContext))]
    [Migration("20260828183609_AddKillRoster")]
    partial class AddKillRoster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VanguardTracker.Api.Models.Boss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RaidId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WarcraftLogsEncounterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaidId", "Order")
                        .IsUnique();

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.EncounterProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BossId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Killed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("KilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessedReportCodesCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PullCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("GuildId", "BossId")
                        .IsUnique();

                    b.ToTable("EncounterProgresses");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Expansion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Expansions");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int?>("DisbandedYear")
                        .HasColumnType("integer");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("text");

                    b.Property<string>("WarcraftLogsGuildName")
                        .HasColumnType("text");

                    b.Property<string>("WarcraftLogsServerRegion")
                        .HasColumnType("text");

                    b.Property<string>("WarcraftLogsServerSlug")
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.Property<string>("YoutubeUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Kill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BossId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<int>("PullCount")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Roster")
                        .HasColumnType("text[]");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("BossId", "GuildId");

                    b.ToTable("Kills");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.PvpTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bracket")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("PlayerNames")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Bracket", "Region");

                    b.ToTable("PvpTeams");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Raid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BossCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("HeroicOpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("MythicOpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NormalOpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Raids");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ExpansionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Boss", b =>
                {
                    b.HasOne("VanguardTracker.Api.Models.Raid", "Raid")
                        .WithMany("Bosses")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.EncounterProgress", b =>
                {
                    b.HasOne("VanguardTracker.Api.Models.Boss", "Boss")
                        .WithMany()
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VanguardTracker.Api.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Kill", b =>
                {
                    b.HasOne("VanguardTracker.Api.Models.Boss", "Boss")
                        .WithMany("Kills")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VanguardTracker.Api.Models.Guild", "Guild")
                        .WithMany("Kills")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Raid", b =>
                {
                    b.HasOne("VanguardTracker.Api.Models.Season", "Season")
                        .WithMany("Raids")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Season", b =>
                {
                    b.HasOne("VanguardTracker.Api.Models.Expansion", "Expansion")
                        .WithMany("Seasons")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Boss", b =>
                {
                    b.Navigation("Kills");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Expansion", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Guild", b =>
                {
                    b.Navigation("Kills");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Raid", b =>
                {
                    b.Navigation("Bosses");
                });

            modelBuilder.Entity("VanguardTracker.Api.Models.Season", b =>
                {
                    b.Navigation("Raids");
                });
#pragma warning restore 612, 618
        }
    }
}
